// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl7dZwgTtPjM4fAolvIHEGGxyVky5e4xA',
    appId: '1:465492826697:web:7681da8019250e4633fd98',
    messagingSenderId: '465492826697',
    projectId: 'four-learn',
    authDomain: 'four-learn.firebaseapp.com',
    storageBucket: 'four-learn.appspot.com',
    measurementId: 'G-PKDHYZ03LY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQBUTcDWhOFzPA5tSNznPQqW13yLQwSXg',
    appId: '1:465492826697:android:a46c080348afc9b033fd98',
    messagingSenderId: '465492826697',
    projectId: 'four-learn',
    storageBucket: 'four-learn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqyKlY-5PwXQ1QzzgnQL667nOFRfg-cN4',
    appId: '1:465492826697:ios:c611d3f7fd4b0bae33fd98',
    messagingSenderId: '465492826697',
    projectId: 'four-learn',
    storageBucket: 'four-learn.appspot.com',
    iosClientId: '465492826697-ecov25ibct5q1fe3fjfl61jdnnsi46cb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFourLearnApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqyKlY-5PwXQ1QzzgnQL667nOFRfg-cN4',
    appId: '1:465492826697:ios:c611d3f7fd4b0bae33fd98',
    messagingSenderId: '465492826697',
    projectId: 'four-learn',
    storageBucket: 'four-learn.appspot.com',
    iosClientId: '465492826697-ecov25ibct5q1fe3fjfl61jdnnsi46cb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFourLearnApp',
  );
}
